trigger:
- main
pool:
  vmImage: 'windows-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
- script: npm ci
- script: npm run test:ci
  displayName: 'Run tests'
- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'junit.xml'
    testRunTitle: 'Jest Tests'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/cobertura-coverage.xml'